[package]
name = "network-utils"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
tempfile = "3"
log = "0.4"

[dev-dependencies]
test-log = "0.2"
